### PR TITLE
Fix docs failure on CI

### PR DESCRIPTION
**Pull request by schillic**

### CODE REVIEW

**Comment by schillic** [comment]
Intermediate result: no models works, `ACC` causes the segmentation fault.

**Comment by mforets** [comment]
should we pin the package to an older version of Documenter / Literate which used to work? i don't know if it's urgent to debug this, since users will anyways read the docs online most of the time

**Comment by schillic** [comment]
We can try, but locally I do not have this error, so I am not sure where it comes from.

**Comment by schillic** [comment]
The culprit is in this block:
```julia
using Plots
import DisplayAs
fig = plot(leg=(0.4, 0.3))
```

**Comment by mforets** [comment]
sice the examples are now "settled" i would not mind if we just remove the DisplayAs stuff. (in fact, on my screen it renders much better without DisplayAs).  the main issue comes from collecting old PR previews but that is covered by the github action.

**Comment by schillic** [comment]
I think it is rather a problem with `Plots` because `Polyhedra` does not use `DisplayAs`. But this needs to be confirmed.

**Review by mforets — APPROVED** [review]

**Pull request merged**
